### ISSUE TITLE
gnome-shell-extension-desktop-icons .file-item styling

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#1091]
@iainlane

The new shell extension styles the selected item color here:
https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/blob/master/stylesheet.css#L12
Which can not be overridden by the shell theme ( I guess because the extension's stylesheet is taken after)

![image](https://user-images.githubusercontent.com/15329494/50823836-3252ea80-1335-11e9-8557-4b7a7ebd3830.png)

The border-radius for example is not styled in the extensions stylesheet, thus I can change it on our shell theme.

The problem I see with it being not a fork is that upstream gnome does not want to use that extension by default. Thus we can't request in the upstream gnome shell repo to add the styling because they don't need it.

I see two solutions:
a) fork it and remove the styling from the fork and add it to our theme
b) request at the extension's repo to search for the @ theme_selected_bg_color in the current theme

Any other ideas @clobrano @iainlane ?

**Comment by iainlane** [comment]
Using variables from the theme would probably work - I checked that bg color and it's the same as @ theme_selected_bg_color with some transparency applied. I think if you have time and were to submit a MR that would hopefully be welcomed. :-)

**Comment by Feichtmeier** [comment]
I see that I can work on that this Eve
I guess when I use the gnome-session I could test it

**Comment by Feichtmeier** [comment]
@iainlane do you have any idea how I can import the colors?
Otherwise I'll better just open an issue on their repo

**Comment by iainlane** [comment]
ah yeah, it's the gnome-shell theme and not the gtk one. that one doesn't have defined public colours. Here's what I can see to do:

gnome-shell will try to load `MODE.css` (MODE defaults to "user" for upstream Shell), and then `stylesheet.css` for each extension, as well as using the main gnome-shell theme.

It should be possible to split the theme-specific bits (colours) out into `user.css` (make sure to `@import url('stylesheet.css');` at the top), leaving the rest in `stylesheet.css`, and then style the colours in the main Yaru GNOME Shell theme.

**Comment by Feichtmeier** [comment]
Yay it works! 
However only in the yaru sesssion :thinking: 
![screenshot from 2019-01-08 18-44-46](https://user-images.githubusercontent.com/15329494/50848809-7ebe1a80-1375-11e9-99df-453be23c9649.png)

In the gnome-session it does work

```css
@import url('stylesheet.css');

.file-item {
    padding: 4px;
    border: 1px;
    margin: 1px;
}

.file-item:hover {
   background-color: rgba(238, 238, 238, 0.2);
}

.file-item:selected {
   background-color: $selected_bg_color;
   border-color: rgba(74, 144, 217, 0.8);
}

.rubber-band {
   background-color: rgba(74, 144, 238, 0.4);
}

.name-label {
    text-shadow: 1px 1px black;
    color: white;
    text-align: center;
}

.draggable {
    background-color: red;
}

.rename-popup {
    min-width: 300px;
    margin: 6px;
}
``` 

Any idea why this does not work for the default gnome shell theme in the gnome-session?
