### ISSUE TITLE
Add support for the folder-rename popup

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/yaru#1526]
It has been introduced recently by GNOME shell upstream ([MR](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/675/diffs#diff-content-d27519967b4ac5df7ae7d6279de3e5ec655a72bf), will be part of 3.34.2)

Adding this should be enough:
```scss
// Rename popup

.rename-folder-popup-box {
  spacing: 6px;
  margin-left: 12px;
  margin-right: 12px;
}

```
