### ISSUE TITLE
Changing Dock behavior to the bottom position and adjusting the background opacity to dynamic doesn't work, another class overlap occurs

### ISSUE THREAD

**Issue by lvitals** [ubuntu/yaru#1649]
## Actual Behavior

Changing Dock behavior to the bottom position and adjusting the background opacity to dynamic doesn't work, another class overlap occurs

![Captura de tela de 2019-12-02 16-48-34](https://user-images.githubusercontent.com/2145794/69992600-c5d27280-1528-11ea-8834-49dacd246196.png)

## Expected Behavior

![Captura de tela de 2019-12-02 17-56-35](https://user-images.githubusercontent.com/2145794/69994711-39767e80-152d-11ea-97c9-8812bbf4b291.png)

## Steps to Reproduce the Problem

  1. Install Ubuntu 19.10 vanilla
  2. run on terminal:

```console
gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode DYNAMIC
gsettings set org.gnome.shell.extensions.dash-to-dock customize-alphas true
gsettings set org.gnome.shell.extensions.dash-to-dock min-alpha 0
gsettings set org.gnome.shell.extensions.dash-to-dock max-alpha 0.8
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
gsettings set org.gnome.shell.extensions.dash-to-dock show-show-apps-button false
gsettings set org.gnome.shell.extensions.dash-to-dock extend-height false
```

## Yaru version

Please report the Yaru version in your system using one of the following commands

    `$ apt show yaru-theme-gnome-shell`

```console
Package: yaru-theme-gnome-shell
Version: 19.10.4
Priority: optional
Section: misc
Source: yaru-theme
Origin: Ubuntu
Maintainer: Ubuntu Desktop Team <ubuntu-desktop@lists.ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 523 kB
Homepage: https://community.ubuntu.com/c/desktop/theme-refresh
Task: ubuntu-desktop-minimal, ubuntu-desktop, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages
Supported: 9m
Download-Size: 109 kB
APT-Manual-Installed: yes
APT-Sources: http://br.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
Description: Yaru GNOME Shell desktop theme from the Ubuntu Community
 This is the theme that is shaped by the community on the Ubuntu hub.
 .
 This package contains the GNOME Shell theme part
 .
 If you want to follow development, more information here:
 https://community.ubuntu.com/c/desktop/theme-refresh.
```

## Fix problems that prevent opacity for dock

commenting the following class in the files.

```console
gnome-shell/src/dark/gnome-shell-sass/_dock.scss:103
gnome-shell/src/gnome-shell-sass/_dock.scss:103
gnome-shell/src/light/gnome-shell-sass/_dock.scss:103
```

```css
  &.opaque {
    /* Temporary reduce traslucency, see https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/376
     * background-color: transparentize($dash_bg_color, $dash-opaque-alpha-value);
     * transition-duration: 500ms; */
    background-color: $dash_bg_color;
    border-color: rgba(0, 0, 0, 0.4);
  }

  &.transparent {
    /* Temporary traslucency under overview state only. See https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/376
     * background-color: transparentize($dash_bg_color, $dash-alpha-value);
     * transition-duration: 500ms; */
    background-color: $dash_bg_color;
    border-color: rgba(0, 0, 0, 0.1);
    transition-duration: 500ms;

    &:overview {
      background-color: transparentize($dash_bg_color, $dash-alpha-value);
      transition-duration: 500ms;
    }
  }
```

Can these classes be removed?

Thanks!
cc: @madsrh @Feichtmeier @giox069
