### ISSUE TITLE
Improvements to the floating bar

### ISSUE THREAD

**Issue by friendlyapple** [ubuntu/yaru#1791]
I think the floating is too visible.

I suggest that we change the background and the borders and reduce the font size.

**Current floating bar:**
![1](https://user-images.githubusercontent.com/59767069/73070022-951b1380-3eaf-11ea-91af-9928a845eb81.png)

**Suggested floating bar:**
The difference is more visible when using nautilus.

![2](https://user-images.githubusercontent.com/59767069/73070046-a2d09900-3eaf-11ea-9e47-6d0b000f2093.png)

**Used colors:**
![3](https://user-images.githubusercontent.com/59767069/73070051-a6fcb680-3eaf-11ea-95c2-579567e70984.png)

**SCSS:**
yaru/gtk/src/default/gtk-3.20/_apps.scss

```css
paned box.floating-bar {
      font-size: 95%; /* or equivalent em unit or 14px */
      background: #fbfbfb; /* TODO: replace with an existing variable */
      border-style: solid;
      border-color: #d9d9d9; /* TODO: replace with an existing variable */
      border-width: 1px 0 0 1px;
      border-radius: $button_radius 0 0 0;
}
```

The change is slight but it makes the interface cleaner.
