### ISSUE TITLE
Gnome clock should use ubuntu colors

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2224]
## Actual Behavior

![Capture d’écran du 2020-07-04 12-46-44](https://user-images.githubusercontent.com/36476595/86510915-b4658780-bde3-11ea-8821-32525fc2ea5e.png)

## Expected Behavior

![Capture d’écran du 2020-07-04 12-46-32](https://user-images.githubusercontent.com/36476595/86510909-ad3e7980-bde3-11ea-819d-508428de71b1.png)

```
.seconds-label,
.miliseconds-label {
	color: $aubergine;
}
```

I can do a PR if you tell me where put this.

**Comment by Jupiter007-43** [comment]
Same thing with timer:

![Capture d’écran du 2020-07-04 13-22-13](https://user-images.githubusercontent.com/36476595/86511432-770bf480-bdf9-11ea-85ef-91df68bad57f.png)

Updated code:

```
@keyframes clocks-blink {
 	0% { color: #9E9DA1; }
 	100% { color: #924D8B; }
 }

.seconds-label,
.miliseconds-label,
.timer-countdown.timer-running {
	color:#924D8B;
}
```

**Comment by Jupiter007-43** [comment]
I got it, it's in _apps.scss

**Comment by clobrano** [comment]
Hi @Jupiter007-43,

I am not sure we should push custom color this far. Usually we touch the `_apps.scss` file as little as possible, and only for issues, more than forcing styling.

**Comment by Jupiter007-43** [comment]
Sorry, I didn't know. 😓
Where can I put the code?

**Comment by clobrano** [comment]
Oh no worries, I was not lecturing you :smile: 
I just think we should keep the color as it is. If it were a semantic color like "selection", I would agree to fix it, but we don't know whether the developers chose this blue because of Adwaita, or just because they liked it, so I don't see it like a bug.

**Comment by Jupiter007-43** [comment]
There is unfortunately no semantic colors. 
But should be a good idea to open an issue into Clocks repo for ask about this (and maybe add semantic color)? 🤔

**Comment by Jupiter007-43** [comment]
But how does work semantic colors?
Sorry for my ignorance, I'm css savvy but I don't know anything about gtk css.

**Comment by madsrh** [comment]
Yes the blue looks a bit out of place in Ubuntu, but I agree with Carlo. Using the selection color would be a good solution and if possible, providing a patch would make it much more likely to be accepted - if possible.

**Comment by Jupiter007-43** [comment]
Do you mean something like that (into Clocks own css):

```scss
@keyframes clocks-blink {
    0% { color: #9E9DA1; }
    100% { color: @theme_selected_bg_color; }
}

.running-stopwatch .seconds-label,
.running-stopwatch .miliseconds-label,
.timer-countdown.timer-running {
    color: @theme_selected_bg_color;
}
```

![Capture d’écran du 2020-07-05 15-37-08](https://user-images.githubusercontent.com/36476595/86533999-7183dc80-bed5-11ea-8fb4-c97ba125c791.png)
![Capture d’écran du 2020-07-05 15-37-19](https://user-images.githubusercontent.com/36476595/86534000-72b50980-bed5-11ea-8146-0aae62399984.png)

**Comment by Jupiter007-43** [comment]
Also:
```scss
.positive-lap {
    color: @success_color;
}

.negative-lap {
    color: @error_color;
}
```
But the contrast is very bad with dark theme 😓

![Capture d’écran du 2020-07-05 15-40-11](https://user-images.githubusercontent.com/36476595/86534071-d6d7cd80-bed5-11ea-88ee-c7f524c77403.png)
![Capture d’écran du 2020-07-05 15-40-40](https://user-images.githubusercontent.com/36476595/86534083-e48d5300-bed5-11ea-9fcc-26ec8c5e36de.png)
