### ISSUE TITLE
Add soft light border to libhandy apps

### ISSUE THREAD

**Issue by Jupi007** [ubuntu/yaru#3809]
I propose to add a soft border to the libhandy apps (this cannot be done correctly in pure gtk3 apps), to mimic the style of gtk4 windows.

| Current | Proposal |
| --- | --- |
| ![Capture d’écran du 2023-01-05 15-49-35](https://user-images.githubusercontent.com/36476595/210807924-113db750-78d7-467c-ac47-81395c3a5333.png) | ![Capture d’écran du 2023-01-05 15-49-18](https://user-images.githubusercontent.com/36476595/210807933-5f7de795-99d0-43df-b566-f4b5b30e66d0.png) |

CC @ubuntu/yaru-team 

This can be basically done like this:

```scss
// Add an inner border around the window
decoration-overlay {
  box-shadow: inset 0 0 0 1px rgba(255,255,255,0.07);
}

// Remove default headerbar highlight
// Special selector to select all headerbars which has a parent which is near a decoration-overlay,
// so we only remove it in Libhandy apps
decoration-overlay ~ * headerbar {
  box-shadow:none
}
```
