### ISSUE TITLE
Dark Shell Notifications have too bright onClick color

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#4082]
I have forgotten how the css property is named, but when one clicks the notifications in the dark shell they are super bright

![grafik](https://github.com/ubuntu/yaru/assets/15329494/b6a6cf5f-ba8b-4a4a-b4f4-0ff33e082996)

Plus I think the border radius is too small

CC @3v1n0

**Comment by ochi12** [comment]
I will try to look on this

**Comment by ochi12** [comment]
One problem tho as I always say I'm a complete newbie. this is under gnome-shell right?

**Comment by ochi12** [comment]
@Feichtmeier
Why is the gnome-shell-theme.gresource file not being overwritten? the ninja installation doesn't even install it. 
 looked upon `gnome-shell/theme/Yaru` still no gnome-shell-theme.gresource installed

Did I miss something? 
I tried to extract the gnome-shell.css and other variants in that gresource file and looked at the `.notification-banner` entry but it is still the default 6 px. 

I followed the build and install steps
```
$ meson _build
$ ninja -C _build
$ ninja -C _build install
```

even tried to uninstall `yaru-theme-gnome-shell`  then repeated the above commands, looked upon `gnome-shell/theme/Yaru` still no gnome-shell-theme.gresource installed

Did I miss something?

**Comment by Feichtmeier** [comment]
> @Feichtmeier
> Why is the gnome-shell-theme.gresource file not being overwritten? the ninja installation doesn't even install it. 
>  looked upon `gnome-shell/theme/Yaru` still no gnome-shell-theme.gresource installed
> 
> Did I miss something? 
> I tried to extract the gnome-shell.css and other variants in that gresource file and looked at the `.notification-banner` entry but it is still the default 6 px. 
> 
> I followed the build and install steps
> ```
> $ meson _build
> $ ninja -C _build
> $ ninja -C _build install
> ```
> 
> even tried to uninstall `yaru-theme-gnome-shell`  then repeated the above commands, looked upon `gnome-shell/theme/Yaru` still no gnome-shell-theme.gresource installed
> 
> Did I miss something? 

I'm a little out of the loop but the last time I edited the notifications all I needed to change was scss code 
Forwarding this to @3v1n0 and @Muqtxdir

**Comment by ochi12** [comment]
thanks!

**Comment by ochi12** [comment]
Testing this changes if mentioned problems are addressed
```scss
/* Notifications & Message Tray */

$notification_banner_height: 64px;
$notification_banner_width: 34em;

// Banner notifications
.notification-banner {
  min-height: $notification_banner_height;
  width: $notification_banner_width;
  box-shadow: 0 2px 4px 2px $shadow_color;
  border-radius: $yaru_menu_border_radius;  // SAME AS QUICK_SETTINGS RADIUS
  margin: $base_margin;
  background-color: $bg_color; // Yaru change: use bg_color for better contrast with buttons

  @if $contrast == 'high' {
    @include draw_hc_inset();
  }

  &:hover {
    // Yaru change: ↑↑↑
    background-color: if($variant =='light', darken($bg_color, 2%), lighten($bg_color, 2%));
  }

  &:active {
    // Yaru change: ↑↑↑
    background-color: if($variant =='light', darken($bg_color, 4%), lighten($bg_color, 3%)); // LIGHTEN BY 3% INSTEAD OF 4 PERCENT
  }

  // Yaru: make notifications more visible on different headerbars:
  &,
  &:hover,
  &:focus,
  &:active {
    box-shadow: 0 0 4px 2px rgba(0, 0, 0, 0.1);
    border: 1px solid $borders_color;
  }
}

.notification-buttons-bin {
  spacing: 0;
}

.notification-button {
  @extend %notification_button;
}

```
Summary:
- Using `$yaru_menu_border_radius` for the border-radius
- modifying the lighten function from using 4% to 3% . Addresses the `too bright onClick color` issue
